---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "RelEng Notification Policy"
consumes:
  - application/json
produces:
  - application/json
paths:

  /example:
    get:
      operationId: "releng_notification_policy.api.example"
      responses:
        200:
          description: Example
